<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use GuzzleHttp\Exception\GuzzleException;
use GuzzleHttp\Client;

class UrlAnalyticsController extends Controller
{
    //
    public $url;
    public function __construct($url)
    {
        $this->url=$url;
    }
    public function getIBM()
    {

        try {
            $url=$this->url;

        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
            $ch = curl_init();

            curl_setopt($ch, CURLOPT_URL, 'https://gateway.watsonplatform.net/natural-language-understanding/api/v1/analyze?version=2018-11-16');
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
            curl_setopt($ch, CURLOPT_POSTFIELDS, "{ \"url\": \"$url\", \"features\": { \"sentiment\": {}, \"categories\": {}, \"concepts\": {} } }");
            curl_setopt($ch, CURLOPT_POST, 1);
            curl_setopt($ch, CURLOPT_USERPWD, 'apikey' . ':' . config('app.ibm'));

            $headers = array();
            $headers[] = 'Content-Type: application/json';
            curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

            $result = curl_exec($ch);
            if (curl_errno($ch)) {
                echo 'Error:' . curl_error($ch);
            }
            curl_close ($ch);
            return $result;
        }
        catch (\Exception $e)
        {
            $e->getMessage();
        }
    	
    	
    }
    public function checkNLPAvailability()
    {
        
    }
}
